id: A64CF613C
title: The Secret Practice of the Great Compassionate One, Natural Liberation of Suffering
type: translation
pechas:
- I748C72CB
- IBE6E64E9
- I94E4FFF3
source_metadata:
  languages:
  - en
  - de
  - bo
  datatype: PlainText
  created_at: 2023-01-04 12:44:38.345903
  last_modified_at: 2023-01-04 12:44:38.345911
  collections:
  - Jigme Lingpa Series
  - Works of Tibetan Masters
alignment_to_base:
  I748C72CB/9DBC: B789
  IBE6E64E9/3832: B789
  I94E4FFF3/8E90: B789
